//------------------------------------------------------------------------------//
//------------------------------------------------------------------------------//
//              AUTOMATICALLY GENERATED BY SAMPLE POINT GENERATOR               //
//------------------------------------------------------------------------------//
//------------------------------------------------------------------------------//


#pragma once


/// System headers
#include <stdint.h> /// uint32_t


/// Hammersley采样组(SET)的总数
static constexpr uint16_t HAMMERSLEY_SAMPLE_SET_COUNT = 8U;
/// Hammersley每组中采样点(SAMPLE)的总数
static constexpr uint16_t HAMMERSLEY_SET_SAMPLE_COUNT = 1024U;
/// Hammersley采样点(SAMPLE)的总数
static constexpr uint32_t HAMMERSLEY_TOTAL_SAMPLE_COUNT = 8192U;
